
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: never
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
      
  logging:
    level:
      root: ${LOG_LEVEL}